name: Push Python
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Configure Cloudsmith URL
      run: |
        export PIP_INDEX_URL="https://${{ secrets.CLOUDSMITH_AUTOMATION_USER }}:${{ secrets.CLOUDSMITH_API_KEY }}@dl.cloudsmith.io/queeg-5000/blue-midget/python/simple/"
    - name: Install Build package
      id: prereqs
      run: |
        python -m pip install build
        python -m build
    - name: Show version number
      id: version
      run: |
        python -m pip install setuptools
        echo "version=$(python setup.py --version)"
        echo "version=$(python setup.py --version)" >> "$GITHUB_OUTPUT"
    - name: Push
      id: push
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: "push"
        format: "python"
        owner: "queeg-5000"
        repo: "blue-midget"
        republish: "true" # needed ONLY if version is not changing
        file: "dist/fastly_debug-$(python setup.py --version).tar.gz"
